alias ls="ls -G"
alias cat="ccat"
alias cal="gcal"
alias cse="ssh wzheng4@timberlake.cse.buffalo.edu"
alias ccr="ssh wzheng4@rush.ccr.buffalo.edu"
alias rm="trash"
alias c="tr -d '\n' | pbcopy"
alias cs="vim -R ~/trinity/cheat.txt"
alias sl="echo $SHLVL"

alias emacs="ln -svhF ~/.my_emacs.d ~/.emacs.d"
alias spacemacs="ln -svhF ~/.spacemacs.d ~/.emacs.d"

export PATH=$PATH:/Applications/Racket\ v6.9/bin
export EDITOR=/usr/local/bin/vim

# workaround C-a C-e bug on macOS
bindkey -e

